apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "azure-token-generator"
  namespace: "aura"
  labels:
    team: "aura"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/internal/is_alive"
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: "/internal/is_ready"
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "256Mi"
  ingresses:
    - https://azure-token-generator.intern.dev.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
