apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "wonderwalled-idporten"
  namespace: "aura"
  annotations:
    texas.nais.io/enabled: "true"
spec:
  accessPolicy:
    inbound:
      rules:
        - application: wonderwalled-idporten
    outbound:
      rules:
        - application: wonderwalled-idporten
  image: {{image}}
  port: 8080
  liveness:
    path: "/internal/is_alive"
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: "/internal/is_ready"
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "5m"
      memory: "128Mi"
  ingresses:
    - https://wonderwalled-idporten.intern.dev.nav.no
  idporten:
    enabled: true
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: sdk
