apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "wonderwalled-maskinporten"
  namespace: "nais"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/internal/is_alive"
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: "/internal/is_ready"
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "5m"
      memory: "128Mi"
  ingresses:
    - https://wonderwalled-maskinporten.intern.dev.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
    sidecar:
      enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: nav:test/api
  observability:
    autoInstrumentation:
      enabled: true
      runtime: sdk
