apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "wonderwalled"
  namespace: "aura"
  labels:
    team: "aura"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/internal/is_alive"
  readiness:
    path: "/internal/is_ready"
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "256Mi"
  ingresses: 
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
